#!/bin/bash
if [ $# -eq 0 ]; then
    WHICH="-c app"
else
    WHICH="-c $1"
fi
kubectl exec -it -n viewmaster `kubectl get pod -n viewmaster -l tier=app | cut -f1 -d" " | tail -1` ${WHICH} -- /bin/bash
