apiVersion: v1
kind: Service
metadata:
  name: viewmaster
  namespace: viewmaster
  labels:
    app: viewmaster
spec:
  ports:
    - port: 8000
  selector:
    app: viewmaster
    tier: app
  type: LoadBalancer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: viewmaster-app-pvc
  namespace: viewmaster
  labels:
    app: viewmaster
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: viewmaster
  namespace: viewmaster
  labels:
    app: viewmaster
spec:
  selector:
    matchLabels:
      app: viewmaster
      tier: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: viewmaster
        tier: app
    spec:
      volumes:
        - name: viewmaster-app-data
          persistentVolumeClaim:
            claimName: viewmaster-app-pvc
      containers:

        - image: pmichali/viewmaster-app:v0.1.1
          imagePullPolicy: IfNotPresent
          name: app
          ports:
            - containerPort: 8080
              name: app
          volumeMounts:
            - name: viewmaster-app-data
              mountPath: /vol/web
          envFrom:
          - secretRef:
              name: viewmaster-secrets
          - configMapRef:
              name: viewmaster-cm

        # - image: pmichali/viewmaster-proxy:latest
        #   imagePullPolicy: Always
        #   name: proxy
        #   ports:
        #     - containerPort: 8000
        #       name: proxy
        #   volumeMounts:
        #     - name: viewmaster-app-data
        #       mountPath: /vol/web
        #   env:
        #     - name: APP_HOST
        #       value: '127.0.0.1'
        #     - name: APP_PORT
        #       value: '8080'
