# nginx-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: viewmaster-nginx-config
  namespace: viewmaster
data:
  default.conf: |
    # Cache settings
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=django_cache:10m max_size=1g 
                     inactive=60m use_temp_path=off;

    server {
        listen 80;  # Nginx listens on port 80
        # Compression settings
        # Main gzip settings
        gzip on;
        gzip_comp_level 5;  # Balance between CPU and compression (range: 1-9)
        gzip_min_length 256;  # Don't compress very small files
        gzip_proxied any;  # Compress responses from proxied servers
        gzip_vary on;  # Add Vary: Accept-Encoding header

        # Mime types to compress
        gzip_types
            application/javascript
            application/json
            application/xml
            application/xml+rss
            image/svg+xml
            image/jpeg
            text/css
            text/javascript
            text/plain
            text/xml;

        # Disable for IE6 (optional in 2025, but still a good practice)
        gzip_disable "msie6";

        location /media/ {
            alias /vol/web/media/;  # Serve media files from PVC
            expires 1y;
            add_header Cache-Control "public, max-age=31536000, immutable";

            # Optimize for small files, combine small packets, and send directly
            tcp_nodelay on;
            tcp_nopush on;
            sendfile on;

            # Logging off for high-traffic image serving
            access_log off;
        }
        location /static/ {
            alias /vol/web/static/;
            expires 1y;
            add_header Cache-Control "public, max-age=31536000, immutable";

            # Optimize for small files, combine small packets, and send directly
            tcp_nodelay on;
            tcp_nopush on;
            sendfile on;

            # Logging off for high-traffic image serving
            access_log off;
        }
        location / {
            proxy_pass http://127.0.0.1:8080;  # Proxy to Gunicorn on 8080
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # Enable proxy caching
            proxy_cache django_cache;
            proxy_cache_valid 200 302 10m;
            proxy_cache_valid 404 1m;
            proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;

            # Add cache status header for debugging - this is correctly placed here
            # because $upstream_cache_status variable is only available in proxy contexts
            # add_header X-Cache-Status $upstream_cache_status;
        }
    }
