apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: viewmaster-app-pvc
  namespace: viewmaster
  labels:
    app: viewmaster
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
