# Generated by Django 4.2.14 on 2025-02-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewmaster', '0005_alter_movie_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.CharField(blank=True, default='unknown', help_text='IMDB movie ID (imported)'),
        ),
    ]
