# Generated by Django 4.2.14 on 2025-02-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewmaster', '0006_alter_movie_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('ACTION', 'action'), ('ADVENTURE', 'adventure'), ('ANIMATED', 'animated'), ('CHILDRENS', 'childrens'), ('COMEDY', 'comedy'), ('CRIME', 'crime'), ('DOCUMENTARY', 'documentary'), ('DRAMA', 'drama'), ('FAMILY', 'family'), ('FANTASY', 'fantasy'), ('HISTORY', 'history'), ('HORROR', 'horror'), ('MILITARY', 'military'), ('MISC', 'misc'), ('MUSICAL', 'musical'), ('MYSTERY', 'mystery'), ('ROMANCE', 'romance'), ('SCI-FI', 'sci-fi'), ('SUSPENSE', 'suspense'), ('THRILLER', 'thriller'), ('UNKNOWN', 'unknown'), ('WESTERN', 'western')], help_text='Select a genre', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='format',
            field=models.CharField(choices=[('LD', 'LD'), ('DVD', 'DVD'), ('BR', 'BR'), ('4K', '4K')], help_text='Select media format', max_length=3),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('X', 'X'), ('NR', 'NR'), ('?', '?')], default='?', help_text='Select the MPAA rating', max_length=5),
        ),
    ]
