# Generated by Django 4.2.14 on 2025-04-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewmaster", "0007_alter_movie_category_alter_movie_format_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="category",
            field=models.CharField(
                choices=[
                    ("ACTION", "action"),
                    ("ADVENTURE", "adventure"),
                    ("ANIMATED", "animated"),
                    ("BIOGRAPHY", "biography"),
                    ("CHILDRENS", "childrens"),
                    ("COMEDY", "comedy"),
                    ("CRIME", "crime"),
                    ("DOCUMENTARY", "documentary"),
                    ("DRAMA", "drama"),
                    ("FAMILY", "family"),
                    ("FANTASY", "fantasy"),
                    ("HISTORY", "history"),
                    ("HORROR", "horror"),
                    ("MILITARY", "military"),
                    ("MISC", "misc"),
                    ("MUSICAL", "musical"),
                    ("MYSTERY", "mystery"),
                    ("ROMANCE", "romance"),
                    ("SCI-FI", "sci-fi"),
                    ("SUSPENSE", "suspense"),
                    ("THRILLER", "thriller"),
                    ("UNKNOWN", "unknown"),
                    ("WESTERN", "western"),
                ],
                help_text="Select a genre",
                max_length=20,
            ),
        ),
    ]
