# Generated by Django 5.2 on 2025-05-06 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("viewmaster", "0009_imdbinfo_movie_imdb_info"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imdbinfo",
            old_name="rating",
            new_name="mpaa_rating",
        ),
        migrations.RenameField(
            model_name="imdbinfo",
            old_name="release",
            new_name="release_date",
        ),
        migrations.RenameField(
            model_name="imdbinfo",
            old_name="duration",
            new_name="run_time",
        ),
        migrations.RenameField(
            model_name="imdbinfo",
            old_name="title",
            new_name="title_name",
        ),
    ]
