# Generated by Django 4.2.14 on 2025-04-19 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("viewmaster", "0009_moviedetails_alter_movie_category_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="moviedetails",
            unique_together={("title", "source")},
        ),
    ]
