# Generated by Django 4.2.14 on 2025-04-23 18:47

from django.db import migrations


def get_details(movie, DetailsModel):
    """Returns details object associated with movie."""
    try:
        return DetailsModel.objects.get(id=movie.details_id)
    except DetailsModel.DoesNotExist:
        return None


def copy_details_back(apps, schema_editor):
    """Copy details back into movie model (for reverse migration)."""
    Movie = apps.get_model("viewmaster", "Movie")
    MovieDetails = apps.get_model("viewmaster", "MovieDetails")

    total = 0
    restored = 0
    failures = 0
    print("\n\nReverse migrating data...")
    for m in Movie.objects.all():
        total += 1
        details = get_details(m, MovieDetails)
        if not details:
            print(f"ERROR! Missing details for movie ID {m.id} - skipping")
            failures += 1
        else:
            m.title = details.title
            m.release = details.release
            m.category = details.genre
            m.rating = details.rating
            m.duration = details.duration
            m.plot = details.plot
            m.actors = details.actors
            m.directors = details.actors
            m.cover_ref = details.cover_url
            m.movie_id = details.source
            m.save()
            print(f"{m.title} {m.format} Details restored")
            restored += 1
    print(
        "\nSTATS:\n"
        f"    Total:   {total}\n"
        f"    Restored: {restored}\n"
        f"    Failed:  {failures}\n\n"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("viewmaster", "0010_alter_moviedetails_unique_together"),
    ]

    operations = [
        # Do reverse data migration of details back to movie
        migrations.RunPython(migrations.RunPython.noop, copy_details_back),
        migrations.RemoveField(
            model_name="movie",
            name="actors",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="category",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="cover_ref",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="directors",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="movie_id",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="plot",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="release",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="title",
        ),
    ]
