# Generated by Django 5.2 on 2025-04-25 21:44

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewmaster", "0012_moviedetails_cover_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviedetails",
            name="cover_file",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    allow_overwrite=True
                ),
                upload_to="covers",
            ),
        ),
    ]
